name: Deploy Portfolio

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # This is the "build" job you were looking for!
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: 'https://shirley-1107.github.io/Shirley-portfolio/'
          uploadArtifacts: true 
          temporaryPublicStorage: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

  # This is the "deploy" job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
