name: Deploy and Test

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # --- START OF LIGHTHOUSE SECTION ---
      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: 'https://shirley-1107.github.io/Shirley-portfolio/'
          uploadArtifacts: true 
          temporaryPublicStorage: true
      # --- END OF LIGHTHOUSE SECTION ---

      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
